name: Deploy-CDK-Stack/Prod
run-name: Running ${{github.workflow}} off of ${{ github.ref_name }}

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy Production
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production

 