name: Diff-CDK-Stack/Prod
run-name: Running ${{github.workflow}} off of ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  diff:
    name: Diff Production
    uses: ./.github/workflows/diff.yaml
    with:
      environment: production

 