name: Diff CDK
run-name: Running ${{ github.workflow }} off of ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  diff:
    uses: ./.github/workflows/diff.yaml
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}