name: Diff CDK
run-name: Running ${{github.workflow}} off of ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  diffdev:
    name: Diff Development
    if: github.ref_name == 'develop'
    uses: ./.github/workflows/diff.yaml
    with:
      environment: development
  diffprod:
    name: Diff Production
    if: github.ref_name == 'main'
    uses: ./.github/workflows/diff.yaml
    with:
      environment: production

 