name: CDK Lint & Checkov Scan

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write  # Required for annotations

jobs:
  lint-checkov:
    name: Lint & Security Scan
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: src

    env:
      AWS_DEFAULT_REGION: us-east-2

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install CDK and dependencies
        run: |
          npm install -g aws-cdk
          pip install -r requirements.txt
          pip install cfn-lint checkov

      - name: CDK Synth
        run: cdk synth --context environment=development

      - name: Run cfn-lint
        continue-on-error: true
        run: |
          for template in cdk.out/*.template.json; do
            echo "Linting $template"
            cfn-lint "$template"
          done

      - name: Run checkov with GitHub Annotations
        continue-on-error: true
        run: |
            for template in cdk.out/*.template.json; do
            checkov -f "$template"
            done