name: Cleanup Preview Trigger

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  cleanup-preview:
    name: Cleanup Preview
    uses: ./.github/workflows/preview_cleanup.yaml
    with:
      preview_id: pr-${{ github.event.pull_request.number }}
      pr_number: ${{ github.event.pull_request.number }}
